version: '3'

services:
  meu-trocado-bd:
    build:
      context: .
    container_name: unyleya-bd
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=unyleya
      - PGPORT=5432
    volumes:
      - ~/banco-de-dados/unyleya:/var/lib/postgresql/data
